### ISSUE TITLE
System.Exception: Realistic Water Two is not present in the load order, make sure you installed it correctly.

### ISSUE THREAD

**Issue by ghyujkilop** [ReaperAnon/Realistic-Water-Two-Patcher#2]
Compiling
No extra data to consider
("C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\larm0soc.h1c\Runner\RealisticWaterTwoPatcher"): "dotnet" "build \"RealisticWaterTwoPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "48e311a92c4d0c82e56a7c863bdde4352de476e6"
Running
(""): "dotnet" "run --project \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\larm0soc.h1c\Runner\RealisticWaterTwoPatcher\RealisticWaterTwoPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder \"D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Realistic-Water-Two-Patcher\" --GameRelease SkyrimSE --ModKey \"Synthesis 1.esp\" --LoadOrderFilePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis 1\Plugins.txt\" --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis 1\1 - Realistic-Water-Two-Patcher\Synthesis 1.esp\" --PatcherName Realistic-Water-Two-Patcher --SourcePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis 1\1 - MoreGoldForMerchants\Synthesis 1.esp\""
Mutagen version: 0.39.5
Mutagen sha: 4d748874d0485b2d3b9679d21043c316b805654b
Synthesis version: 0.24.1
Synthesis sha: 813636272843a7c16e6684ec66629e516eb78986
Newtonsoft version: 13.0.1+ae9fe44e1323e91bcbd185ca1a14099fba7c021f
run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder "D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Realistic-Water-Two-Patcher" --GameRelease SkyrimSE --ModKey "Synthesis 1.esp" --LoadOrderFilePath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis 1\Plugins.txt" --LoadOrderIncludesCreationClub --OutputPath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis 1\1 - Realistic-Water-Two-Patcher\Synthesis 1.esp" --PatcherName Realistic-Water-Two-Patcher --SourcePath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis 1\1 - MoreGoldForMerchants\Synthesis 1.esp"
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
System.Exception: Realistic Water Two is not present in the load order, make sure you installed it correctly.
   at RealisticWaterTwoPatcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\larm0soc.h1c\Runner\RealisticWaterTwoPatcher\Program.cs:line 27
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass13_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 100
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 565
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 462
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass37_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 425

I think this doesn't work. I definitely have RW2 in my load order, and all other patchers work fine.

**Comment by erlunsford** [comment]
I've got the same issue. It was working before today, but stopped. It seems the plugins.txt file it's using doesn't represent the whole list of enabled plugins for some reason. It includes RealisticWaterTwo - Resources.esm, but not RealisticWaterTwo.esp.
